### PR TITLE
java: Use Optional<T> to indicate optional values

### PR DESCRIPTION
**Pull request by mpkorstanje**
Permanently avoid the problems from https://github.com/cucumber/cucumber-jvm/issues/2454

### CODE REVIEW

**Comment by mpkorstanje** [comment]
@aslakhellesoy in Javascript `buildNumber` is not optional:

https://github.com/cucumber/ci-environment/blob/main/javascript/src/types.ts#L4

However the value is evaluated from an expression and may be null. Which one is correct?

**Review by aslakhellesoy — APPROVED** [review]
Great!! This will teach me to use `Optional` :-)

**Comment by aslakhellesoy** [comment]
> @aslakhellesoy in Javascript `buildNumber` is not optional:
> 
> https://github.com/cucumber/ci-environment/blob/main/javascript/src/types.ts#L4
> 
> However the value is evaluated from an expression and may be null. Which one is correct?

Good catch. I think we should allow `null` for that field. Working on a fix...

**Comment by aslakhellesoy** [comment]
> > @aslakhellesoy in Javascript `buildNumber` is not optional:
> > https://github.com/cucumber/ci-environment/blob/main/javascript/src/types.ts#L4
> > However the value is evaluated from an expression and may be null. Which one is correct?
> 
> Good catch. I think we should allow `null` for that field. Working on a fix...

Fixed in #51

**Comment by mpkorstanje** [comment]
> Great!! This will teach me to use Optional :-)

It's relatively simple. Only ever use it as a return type. Don't use it as an argument. When used as a return type, never return null.

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html

**Pull request merged**
