### PR TITLE
Make buildNumber optional

### PR DESCRIPTION
**Pull request by aslakhellesoy**
# Description

Make `buildNumber` an optional field.

# Motivation & context

The TypeScript definition of `CiEnvironment` incorrectly declared the field as mandatory, but at runtime it may be optional.

## Type of change

- Breaking change (will cause existing functionality to not
  work as expected)

# Checklist:

- [x] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
So what about messages? It is required there.

**Comment by aslakhellesoy** [comment]
When we added the field in [17.0.0](https://github.com/cucumber/common/blob/main/messages/CHANGELOG.md#1700---2021-07-08) it was a mistake to define this field as mandatory.

It was a mistake because consumers have to handle previous versions of messages where the field would always be absent. As a general rule, we should *always* declare new fields as optional in order to be able to handle older versions.

So I propose:
* We make a new messages release where the field is optional. It's debatable whether it is a bugfix or a breaking change - I'm leaning towards bugfix in this case.
* I update this PR to make it optional here too.

It's a real shame [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference) doesn't generate `Optional` getters for non-required fields. There is an open PR for it: https://github.com/joelittlejohn/jsonschema2pojo/pull/1057. We could fork and release our own maven package, or we could abandon it altogether and use custom code generation like we do for TypeScript, Go and Ruby. I think maybe the latter.

WDYT?

**Comment by aurelien-reeves** [comment]
Well, I don't know with java. But in the schema, and in js and ruby implementation, the build number is not mandatory in messages

**Comment by aslakhellesoy** [comment]
You're right @aurelien-reeves - it's not required. What made you think it was required @mpkorstanje?

**Comment by mpkorstanje** [comment]
Ah. My bad. That should have been a question, not an assertion.

So we're good.

**Comment by mpkorstanje** [comment]
> It's a real shame jsonschema2pojo doesn't generate Optional getters for non-required fields. There is an open PR for it: joelittlejohn/jsonschema2pojo#1057. We could fork and release our own maven package, or we could abandon it altogether and use custom code generation like we do for TypeScript, Go and Ruby. I think maybe the latter.

One thing at a time.

**Review by mpkorstanje — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
@mpkorstanje I wasn't quite ready with this PR, ref my suggestion above to make `buildNumber` optional. Please don't release this until I have fixed that.

**Comment by mpkorstanje** [comment]
Not sure what you mean. I did see `buildNumber?: string`  so I assume you made it optional.

**Comment by aslakhellesoy** [comment]
You're right - ignore me. Getting my wires crossed.

**Pull request merged**
