### PR TITLE
CI: Keep two JS versions in matrix, and Node 16

### PR DESCRIPTION
**Pull request by olleolleolle**
### 🤔 What's changed?

This PR removes a few older Node.js versions from the CI matrix.

- Use 18 (the LTS) for other platforms
- Node 18 LTS
- Node 20 latest release
- and, until September 11th, 2023, Node 16

### ⚡️ What's your motivation? 

The JS ecosystem moves on, and packages no longer support the oldest things.

The Cucumber CI runners are a limited resource.

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### ♻️ Anything particular you want feedback on?

Is 'keep latest 2' a good policy?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by davidjgoss** [comment]
Thanks for doing this.

Node.js 16 is still in maintenance LTS and accordingly we’ll still support it in cucumber-js until it’s EOL date. Given the nature and scope of this project I’m fine with only having 18 and 20, but worth bearing in mind for other more pivotal components.

**Comment by olleolleolle** [comment]
Learned: "Changing the End-of-Life Date for Node.js 16 to September 11th, 2023"

Alright, let me just add it in.

**Comment by olleolleolle** [comment]
@davidjgoss There, reinstated!

**Review by davidjgoss — APPROVED** [review]
LGTM, thanks for updating!

**Pull request merged**
