### PR TITLE
Perepare release to PyPi

### PR DESCRIPTION
**Pull request by elchupanebrej**
### 🤔 What's changed?

Fixup pyproject.toml to conform with the existing release

### ⚡️ What's your motivation? 

I want to have PyPi released continuously.  
### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Review by mpkorstanje — COMMENTED** [review]
We have a release process setup through Github actions. This means that in essence, we only have to set the version number for each implementation and push a git tag (all automated through https://github.com/cucumber/polyglot-release).

So to get the release process working again, I suppose you would have to take your manual instructions and convert them into a Github action.

As a template you could use this commit https://github.com/cucumber/ci-environment/commit/b00f19a0ab71a438bf65cefe52379b59613e9fb3 in which I disabled the python release process (https://github.com/cucumber/ci-environment/issues/213).

**Comment by mpkorstanje** [comment]
Heya. @brasmusson  has been setting up publishing to PyPi using trusted publishers. This is the ideal solution.

https://github.com/cucumber/cucumber-expressions/pull/263

Apologies for changing the optimal solution. Things is are changing atypically quick.

**Comment by luke-hill** [comment]
@elchupanebrej - This probably should have been looked at a while ago. Looking at the 2 linked by @mpkorstanje - it seems as though there is a specific action that is used called `pypa/gh-action-pypi-publish@release/v1` - Can we try use that here for standardisation?

**Comment by luke-hill** [comment]
No longer required

**Pull request closed without merging**
